"""Add nonce table

Revision ID: fec36cb9b0a8
Revises: da54c93e496e
Create Date: 2026-06-07 23:18:13.253548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fec36cb9b0a8'
down_revision: Union[str, Sequence[str], None] = 'da54c93e496e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nonces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('wallet_address', sa.String(length=56), nullable=False),
    sa.Column('nonce_message', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nonces_id'), 'nonces', ['id'], unique=False)
    op.create_index(op.f('ix_nonces_wallet_address'), 'nonces', ['wallet_address'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nonces_wallet_address'), table_name='nonces')
    op.drop_index(op.f('ix_nonces_id'), table_name='nonces')
    op.drop_table('nonces')
    # ### end Alembic commands ###
